ALTER TABLE shopitems ADD COLUMN pic1 VARCHAR(10) NOT NULL DEFAULT 'pic_1';
ALTER TABLE shopitems ADD COLUMN pic2 VARCHAR(10) NOT NULL DEFAULT 'pic_2';
ALTER TABLE shopitems ALTER COLUMN pic1 DROP DEFAULT;
ALTER TABLE shopitems ALTER COLUMN pic2 DROP DEFAULT;

ALTER TABLE shopitems ADD CONSTRAINT art1_fk FOREIGN KEY (pic1) REFERENCES art (key);
ALTER TABLE shopitems ADD CONSTRAINT art2_fk FOREIGN KEY (pic2) REFERENCES art (key);